In [1]:
import numpy as np


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x*(1-x)

In [4]:
training_inputs=np.array([[1,0,0],[0,1,1],[1,0,1],[0,1,0]])
training_inputs

array([[1, 0, 0],
       [0, 1, 1],
       [1, 0, 1],
       [0, 1, 0]])

In [5]:
training_output=np.array([[1,0,1,0]]).T     # T used to transpose rows to columns
training_output

array([[1],
       [0],
       [1],
       [0]])

In [6]:
weights=np.array([[0],[0],[0]],dtype='float64')
weights

array([[0.],
       [0.],
       [0.]])

In [7]:
# Training of neural network
for i in range(1000):
    input_layer=training_inputs
    outputs=sigmoid(np.dot(input_layer,weights))
    error=training_output-outputs
    adjustments=error*sigmoid_derivative(outputs)
    weights=weights+np.dot(input_layer.T,adjustments)
outputs

array([[0.9836679],
       [0.0163321],
       [0.9836679],
       [0.0163321]])