In [3]:
print("Nitesh Babu")

Nitesh Babu


In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b=np.array([[1,2,3],[4,5,6]])
print(b)    

[[1 2 3]
 [4 5 6]]


In [12]:
# ndim:- ndim is used to find dimension of an array
print(a.ndim)
print(b.ndim)

1
2


In [13]:
# dtype:- is used to find data type of numpy array
print(a.dtype)
print(b.dtype)

int64
int64


In [16]:
#itemsize:-itemsize is used to find itemsize of numpy array
print(a.itemsize)
print(b.itemsize)

8
8


In [18]:
#shape:-shape is used to find shape of numpy array
print(a.shape)
print(b.shape)


(3,)
(2, 3)


In [19]:
#size:-size is used to find element of numpy array
print(a.size)
print(b.size)

3
6


In [23]:
#reshape():-it is a function which is used to change the shape of numpy array
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [24]:
#max()
#min()
#sum()
print(a.max())
print(a.min())
print(a.sum())

3
1
6
